package com.ironhack.menuservice.enums;

public enum ReportCommands {
    SALESREP("SALESREP"),
    PRODUCT("PRODUCT"),
    COUNTRY("COUNTRY"),
    CITY("CITY"),
    INDUSTRY("INDUSTRY"),
    EMPLOYEE("EMPLOYEE"),
    QUANTITY("QUANTITY"),
    OPPORTUNITY("OPPORTUNITY"),
    REPORT_LEAD_BY_SALESREP("REPORT LEAD BY SALESREP"),
    REPORT_OPP_BY_SALESREP("REPORT OPPORTUNITY BY SALESREP"),
    REPORT_CLOSE_W_BY_SALESREP("REPORT CLOSED-WON BY SALESREP"),
    REPORT_CLOSE_L_BY_SALESREP("REPORT CLOSED-LOST BY SALESREP"),
    REPORT_OPEN_BY_SALESREP("REPORT OPEN BY SALESREP"),
    REPORT_OPP_BY_PRODUCT("REPORT OPPORTUNITY BY PRODUCT"),
    REPORT_CLOSE_W_BY_PRODUCT("REPORT CLOSED-WON BY PRODUCT"),
    REPORT_CLOSE_L_BY_PRODUCT("REPORT CLOSED-LOST BY PRODUCT"),
    REPORT_OPEN_BY_PRODUCT("REPORT OPEN BY PRODUCT"),
    REPORT_OPP_BY_COUNTRY("REPORT OPPORTUNITY BY COUNTRY"),
    REPORT_CLOSE_W_BY_COUNTRY("REPORT CLOSED-WON BY COUNTRY"),
    REPORT_CLOSE_L_BY_COUNTRY("REPORT CLOSED-LOST BY COUNTRY"),
    REPORT_OPEN_BY_COUNTRY("REPORT OPEN BY COUNTRY"),
    REPORT_OPP_BY_CITY("REPORT OPPORTUNITY BY CITY"),
    REPORT_CLOSE_W_BY_CITY("REPORT CLOSED-WON BY CITY"),
    REPORT_CLOSE_L_BY_CITY("REPORT CLOSED-LOST BY CITY"),
    REPORT_OPEN_BY_CITY("REPORT OPEN BY CITY"),
    REPORT_OPP_BY_INDUSTRY("REPORT OPPORTUNITY BY INDUSTRY"),
    REPORT_CLOSE_W_BY_INDUSTRY("REPORT CLOSED-WON BY INDUSTRY"),
    REPORT_CLOSE_L_BY_INDUSTRY("REPORT CLOSED-LOST BY INDUSTRY"),
    REPORT_OPEN_BY_INDUSTRY("REPORT OPEN BY INDUSTRY"),
    MEAN_EMPCOUNT("MEAN EMPLOYEECOUNT"),
    MEDIAN_EMPCOUNT("MEDIAN EMPLOYEECOUNT"),
    MAX_EMPCOUNT("MAX EMPLOYEECOUNT"),
    MIN_EMPCOUNT("MIN EMPLOYEECOUNT"),
    MEAN_QUANT("MEAN QUANTITY"),
    MED_QUANT("MEDIAN QUANTITY"),
    MAX_QUANT("MAX QUANTITY"),
    MIN_QUANT("MIN QUANTITY"),
    MEAN_OPPS_PERR_ACC("MEAN OPPS PER ACCOUNT"),
    MED_OPPS_PERR_ACC("MEDIAN OPPS PER ACCOUNT"),
    MAX_OPPS_PERR_ACC("MAX OPPS PER ACCOUNT"),
    MIN_OPPS_PERR_ACC("MIN OPPS PER ACCOUNT"),
    BACK("BACK"),
    MAIN_MENU("MAIN MENU"),
    QUIT("QUIT"),
    NONE("");

    public String value;

    ReportCommands(String value) {
        this.value=value;
    }

    public static ReportCommands getCommandType(String cValue) {
        for (ReportCommands command: values()) {
            if(command.value.equals(cValue))
                return command;
        }
        return ReportCommands.NONE;
    }

}
